version: '3.8'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sa_db
    ports:
        - "3307:3306"        
    volumes:      
      - ./mysql/data:/var/lib/mysql 
      - "./setup.sql:/docker-entrypoint-initdb.d/1.sql"        
  web:
    build: .
    ports:
      - "5000:5000"  
volumes:
  volumendb: