version: '3.8'
services:
  clientehost:    
    build: ./cliente
    container_name: clientehost
  repartidor:
    build: ./repartidor
    container_name: repartidorhost    
  restaurante:
    build: ./restaurante
    image: sa/restaurante:latest    
    container_name: restaurantehost    
  esbhost:
    build: ./esb
    container_name: esbhost
    ports:
      - "8080:8080"    